### ISSUE TITLE
bf luis:convert: Error of "Roles must be unique across entity types." triggers by having multiple enabledForAllModels 

### ISSUE THREAD

**Issue by dawwa** [microsoft/botframework-cli#789]
## Versions
@microsoft/botframework-cli/4.8.0 win32-x64 node-v12.16.3
Windows 10

## Describe the bug
Having more than 1 phrase list declaration with enabledForAllModels annotation will cause the CLI errors out.

> [ERROR] line 7:0 - line 7:60: Roles must be unique across entity types. Invalid role definition found "my_gpl(interchangeable)". Prior definition - '@ phraselist Iam_gpl(interchangeable) hasRoles enabledForAllModels'

## To Reproduce
```
@ phraselist Iam_gpl(interchangeable) enabledForAllModels =
	- I
	- I'm
	- I am
	- I be

@ phraselist my_gpl(interchangeable) enabledForAllModels =
	- my
	- mine
	- me
```

**Comment by vishwacsena** [comment]
This appears to be core LU issue.

**Comment by dawwa** [comment]
I tried to export a lu from LUIS portal, which does contain multiple enabledForAllModels, and that lu cannot be processed by the CLI due to this error

**Comment by devedse** [comment]
@vishwacsena , @benbrown, @dawwa,

Hi all, I ran a test where I export a .LU file in the LUIS portal (eu.luis.ai) and then directly import it again. I also run into this issue then:

![image](https://user-images.githubusercontent.com/2350015/84783809-e4dab280-afe9-11ea-987e-1be6bc587e5a.png)

This is line 423:
```
@ phraselist Rate(interchangeable) enabledForAllModels = 
	- rate,interestrate,interest rate,percentage
```

Is this currently a bug in LUIS?

**Comment by vishwacsena** [comment]
@devedse Yes. This issue was fixed in the latest BF-LU package but is not yet available in LUIS portal. I'm working with LUIS team to address this. In the mean time, rather than exporting directly in .lu format from the LUIS portal, you could use `bf luis:convert` as a workaround.

**Comment by vishwacsena** [comment]
@devedse LUIS team is tracking a deployment with this fix for next week.

**Comment by cahann** [comment]
the deployment has rolled out, please confirm if the issue is resolved.

**Comment by devedse** [comment]
@cahann , nope it's still broken:

![image](https://user-images.githubusercontent.com/2350015/86340332-03c97d80-bc55-11ea-87dc-3c9f954efd7f.png)

**Comment by cahann** [comment]
but this time i see I different error, it seems there is a cyclic dependency. InAdance is used as feature to InAdance

**Comment by vishwacsena** [comment]
@devedse if able, can you export your application as JSON and share it? This will help root cause the issue. 

I just verified that the following LU content round trips (import and exports) via the LUIS portal. To @cahann there appears to be a different issue past the one originally reported here. 

```markdown
@ phraselist Rate(interchangeable) enabledForAllModels = 
	- rate,interestrate,interest rate,percentage

> !# @app.name = testImport
```

**Comment by devedse** [comment]
@vishwacsena , I've uploaded the .json file on the "Secure File Transfer" link that was shared by K. Jahagirdar. I'll ask her to share it with you.

**Comment by vishwacsena** [comment]
@devedse thanks for sharing the application json. I looked into the it and the issue is caused because of the occurrence of an ML entity as well as phraseLists with the same name. Although the LUIS portal supports this, there is no good way to have this be supported in the LU format without compromising readability of the content in LU format. 

So the fix here would be for the phraseLists to all have a prefix or suffix e.g. `InAdvance` for the ML entity and `InAdvancePL` for the phrase list and that would address the issue you are seeing when exporting to the LU format. 

Marking this as closed. Please reply here if you continue to see an issue and I can reactivate the thread.

**Comment by devedse** [comment]
@vishwacsena , thanks for your explanation. I think it would be a very good idea to add some information in the error messages / luis portal / when defining a luis model to prevent users from running into the same problem. Would it be a good idea to leave this issue open until that's fixed?

**Comment by vishwacsena** [comment]
@cahann can you comment how you would like to track this?

**Comment by cahann** [comment]
I added to our backlog of issues with error messages. Its one of the top things we want to improve in V4 APIs
